language: objective-c
osx_image: xcode10.1
env: SWIFT_SNAPSHOT=4.2

branches:
only:
- develop

env:

  - ACTION=test  PLATFORM=iOS     DESTINATION='platform=iOS Simulator,name=iPhone 6S'

script:
  - set -o pipefail && xcodebuild -scheme STKitSwift -destination "$DESTINATION" $ACTION | xcpretty

