project 'STKitSwiftDemo.xcodeproj'
platform :ios, '12.0'

target 'STKitSwiftDemo' do
  use_frameworks!
  
  pod 'STKitSwift', :path => '../'
#  pod 'SwiftLint', '~> 0.32.0'
  pod 'SnapKit', '~> 5.0.0'
end
